package com.javanunes;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ricardo
 */
public class View extends javax.swing.JFrame  {

    /**
     * Creates new form View
     */
    public View() { 
        initComponents();
        this.setResizable(false);
        txtHora1.setText(Arquivo.getHoras(1));
        txtHora2.setText(Arquivo.getHoras(2));
        txtHora3.setText(Arquivo.getHoras(3));
        txtHora4.setText(Arquivo.getHoras(4));
        txtHora1.setColumns(5);
        txtHora2.setColumns(5);
        txtHora3.setColumns(5);
        txtHora4.setColumns(5);
      
    }
    
   
    private boolean temEspacosHoras(){
        if( txtHora1.getText().contains(" ") ){
            JOptionPane.showMessageDialog (null, "Primeiro horário contem espaço!");
            txtHora1.grabFocus();
            return true;
        }
        
        if( txtHora2.getText().contains(" ") ){
            JOptionPane.showMessageDialog (null, "Segundo horário contem espaço!");
            txtHora2.grabFocus();
            return true;
        }
        
        if( txtHora3.getText().contains(" ") ){
            JOptionPane.showMessageDialog (null, "Terceiro horário contem espaço!");
            txtHora3.grabFocus();
            return true;
        }
        
        if( txtHora4.getText().contains(" ") ){
            JOptionPane.showMessageDialog (null, "Quarto horário contem espaço!");
            txtHora4.grabFocus();
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btComecar = new javax.swing.JButton();
        txtHora1 = new javax.swing.JTextField();
        txtHora2 = new javax.swing.JTextField();
        txtHora3 = new javax.swing.JTextField();
        lbHora1 = new javax.swing.JLabel();
        lbHora2 = new javax.swing.JLabel();
        lbHora3 = new javax.swing.JLabel();
        javax.swing.JLabel lbTreino = new javax.swing.JLabel();
        txtHora4 = new javax.swing.JTextField();
        lbHora4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btComecar.setText("Começar");
        btComecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComecarActionPerformed(evt);
            }
        });

        txtHora1.setText("00:00");

        txtHora2.setText("00:00");

        txtHora3.setText("00:00");
        txtHora3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHora3ActionPerformed(evt);
            }
        });

        lbHora1.setText("...");

        lbHora2.setText("...");

        lbHora3.setText("...");

        lbTreino.setText("Treino");

        txtHora4.setText("00:00");
        txtHora4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHora4ActionPerformed(evt);
            }
        });

        lbHora4.setText("...");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("JNS Alarme");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHora3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHora1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbHora2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbHora3))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTreino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHora4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbHora4))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btComecar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbHora2)
                                    .addComponent(txtHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTreino)
                            .addComponent(lbHora3)
                            .addComponent(txtHora4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHora4)
                            .addComponent(txtHora3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHora1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(btComecar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHora3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHora3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHora3ActionPerformed

    private void btComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComecarActionPerformed
        // TODO add your handling code here:
        
        // Se as horas que o usuario colocou não tem espaços
        if(!temEspacosHoras()){
            
             // Chama a thread t para ficar conferindo quando o horário é igual ao que usuario inseriu
             Clock hora = new Clock();
             Thread t = new Thread(hora);
             t.start();

             btComecar.setEnabled(false);
             txtHora1.setEditable(false);
             txtHora2.setEditable(false);
             txtHora3.setEditable(false);
             txtHora4.setEditable(false);

             // Salva as horas inseridas pelo usuario em um arquivo
             Arquivo.setHoras(txtHora1.getText(), txtHora2.getText(), txtHora3.getText(), txtHora4.getText());
        }
    }//GEN-LAST:event_btComecarActionPerformed

    private void txtHora4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHora4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHora4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btComecar;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel lbHora1;
    public static javax.swing.JLabel lbHora2;
    public static javax.swing.JLabel lbHora3;
    public static javax.swing.JLabel lbHora4;
    public static javax.swing.JTextField txtHora1;
    public static javax.swing.JTextField txtHora2;
    public static javax.swing.JTextField txtHora3;
    public static javax.swing.JTextField txtHora4;
    // End of variables declaration//GEN-END:variables
}
